/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./screens/*.{js,jsx,ts,tsx}",
    "./screens/customer/*.{js,jsx,ts,tsx}",
    "./screens/producer/*.{js,jsx,ts,tsx}",
    "./components/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./components/cards/*.{js,jsx,ts,tsx}",
    "./components/modals/*.{js,jsx,ts,tsx}",
    "./components/bottomSheets/*.{js,jsx,ts,tsx}",
    "./components/utils/*.{js,jsx,ts,tsx}",
    "./components/utils/badges/*.{js,jsx,ts,tsx}",
    "./components/utils/buttons/*.{js,jsx,ts,tsx}",
    "./components/utils/inputs/*.{js,jsx,ts,tsx}",
    "./components/map/*.{js,jsx,ts,tsx}",
    "./components/utils/texts/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#98B66E",
        secondary: "#262E20",
        lightbg: "#FCFFF0",
        darkbg: "#262E20",
        tertiary: "#444C3D",
        danger: "#942911",
        warning: "#D16014",
        success: "#0081A7",
        night: "#0A090B",
        premium: "#FAA200",
        premiumbg: "#686B65",
        greener: "#006045",
        pending: "#0C0A09",
        partialValidated: "#51344d",
        validated: "#6F5060",
        partialWithdrawn: "#488286",
        withdrawn: "#60A4A9",
        partialCanceled: "#BA2D0B",
        canceled: "#EA2B1F",
      },
    },
  },
  plugins: [],
};
